// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKFU7hS0naBEhjN0zXhccqj7qOU8zkcw8',
    appId: '1:165985692815:web:b9c5162dd925be6a16d4fa',
    messagingSenderId: '165985692815',
    projectId: 'spicebox-133b4',
    authDomain: 'spicebox-133b4.firebaseapp.com',
    storageBucket: 'spicebox-133b4.firebasestorage.app',
    measurementId: 'G-KSRHFLJMYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-BzK1zF4Lo_kzQCcI_l381Z_d3aono2o',
    appId: '1:165985692815:android:e4efbe44db99c1da16d4fa',
    messagingSenderId: '165985692815',
    projectId: 'spicebox-133b4',
    storageBucket: 'spicebox-133b4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALLWKajPGF7QzR9kEMhO0ivxo0saXBm1E',
    appId: '1:165985692815:ios:809ddfc3d27b689e16d4fa',
    messagingSenderId: '165985692815',
    projectId: 'spicebox-133b4',
    storageBucket: 'spicebox-133b4.firebasestorage.app',
    iosBundleId: 'com.spicebox.spicebox',
  );
}
